version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
      - worker
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      - POSTGRES_DB=Newsapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis:
    image: redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run celery -A newsapp worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
