version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: on-failure
    depends_on:
      - db
      - redis
      - worker
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      - POSTGRES_DB=Newsapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis:
    image: redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A newsaggregator worker --loglevel=info
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - db
      - redis

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A newsaggregator beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - db
      - redis
