# Generated by Django 4.2.3 on 2023-07-12 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='TopHeadlines',
        ),
    ]
