# Generated by Django 4.2.3 on 2023-07-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_topheadlines_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadlines',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='topheadlines',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='topheadlines',
            name='url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='topheadlines',
            name='urlToImage',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
