# Generated by Django 4.2.3 on 2023-07-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_topheadlines_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadlines',
            name='url',
            field=models.URLField(max_length=10000, null=True),
        ),
    ]
