# Generated by Django 4.2.3 on 2023-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_publishedat_topheadlines_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeStatisticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_results', models.IntegerField()),
            ],
        ),
    ]
