# Generated by Django 4.2.3 on 2023-07-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_volumestatisticsdaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadlines',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('entertainment', 'Entertainment'), ('general', 'General'), ('health', 'Health'), ('science', 'Science'), ('sports', 'Sports'), ('technology', 'Technology')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topheadlines',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='topheadlines',
            name='source_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topheadlines',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
